### ISSUE TITLE
Search returning None

### ISSUE THREAD

**Issue by kirkkwang** [thomasbreydo/movieposters#1]
Thanks for your work on this!  I can't seem to make it work, it keeps returning nothing, either by title or id.  Not sure what I'm doing wrong.

**Comment by thomasbreydo** [comment]
Hi there—I haven't updated this repo in a while, and it seems as though IMDb has changed its website, breaking `movieposters`. This is bound to happen with any scraper. Unfortunately, I don't have the time to look into this right now, but I'm happy to review a pull request if you'd like to contribute :)

**Comment by thomasbreydo** [comment]
Hi, @kirkkwang — just wanted to let you know that I've fixed the issue!

**Comment by kirkkwang** [comment]
Awesome thank you so much!
