### ISSUE TITLE
Tv show posters no longer week as of few days ago. 

### ISSUE THREAD

**Issue by nickheyer** [thomasbreydo/movieposters#4]
Maybe there was an update that broke it, but I was previously able to get tv-show posters using the same method that is used for movie posters. As of a few days ago, this no longer works. 

If possible, add that functionality back. It was a great help!

**Comment by thomasbreydo** [comment]
Hi @nickheyer, sorry about the delayed response. I've just pushed a fix to the package, perhaps you could try now? If the issue persists, show me the code you're using and I'll happily take a look!

Just make sure to update to version 0.0.7 before trying again.

**Comment by thomasbreydo** [comment]
I'm going to close this issue for now, but feel free to open a new issue if the error persists :)

-Thomas
